title: "DAI Publications"
baseurl: ""
description: "By freely sharing what we learn, we have built a reputation as thought leaders who translate ideas into action and action into results."
url: ""
nav-util:
  - text: FAQ
    link: https://www.dai.com/faq
  - text: SIGN UP
    link: https://www.dai.com/sign-up
  - text: CONTACT US
    link: https://www.dai.com/contact-us
  - text: PROJECT LOGIN
    link: https://www.dai.com/project-login
  - text: JOBS
    link: https://www.dai.com/careers/working-at-dai
nav-main:
  - text: Who We Are
    link: https://www.dai.com#who-we-are
  - text: Our Work
    link: https://www.dai.com#our-work
  - text: Publications
    link: https://www.dai.com#stories
  - text: News
    link: https://www.dai.com#news
  - text: Careers
    link: https://www.dai.com/careers/working-at-dai
nav-main-who:
  - text: Mission & Values
    link: https://www.dai.com/who-we-are/mission-and-values
  - text: History
    link: https://www.dai.com/who-we-are/history
  - text: Leadership
    link: https://www.dai.com/who-we-are/leaders
    children: https://www.dai.com/who-we-are/board
  - text: Global Offices
    link: https://www.dai.com/who-we-are/global
  - text: Our Team
    link: https://www.dai.com/who-we-are/the-team
    children: team
  - text: Ethics & Integrity
    link: /who-we-are/ethics-integrity
nav-main-working:
  - text: Working at DAI
    link: https://www.dai.com/careers/working-at-dai
  - text: Benefits
    link: https://www.dai.com/careers/benefits
  - text: Career Areas
    link: https://www.dai.com/careers/career-areas
  - text: DAI People
    link: https://www.dai.com/careers/dai-people
  - text: Why DAI
    link: https://www.dai.com/careers/why-dai
nav-main-our:
  - text: Solutions
    link: https://www.dai.com/our-work/the-solutions
    children: https://www.dai.com/our-work/solutions
  - text: Regions
    link: https://www.dai.com/our-work/the-regions
    children: https://www.dai.com/our-work/regions
  - text: Projects
    link: https://www.dai.com/our-work/the-projects
    children: https://www.dai.com/our-work/projects
  - text: Our Clients
    link: https://www.dai.com/our-work/our-clients
  - text: Working with DAI
    link: https://www.dai.com/our-work/working-with-us
nav-main-news:
  - text: View More News
    link: https://www.dai.com/news/view-more-news
nav-main-publications:
  - test: Blog Posts
    link: /
  - text: Developments Blog
    link: /developments
  - text: Digital@DAI Blog
    link: https://dai-global-digital.com/
  - text: GH Resource Library
    link: https://www.dai.com/resource-library
  - text: Nigeria Resource Library
    link: https://www.dai.com/nigeria-resource-library