[build]
  command = "npm run build"
  publish = "dist"
  # functions = "./src/functions"

[context.production]
  environment = { NODE_VERSION = "12.18.0", NODE_ENV = "production" }


[dev]
  command = "npm run start"
  framework = "#custom"
  publish = "dist"
  port = 3000
  targetPort = 8181
  NODE_ENV = "development"
  # functionsPort = 34567

[[redirects]]
  from = ""
  to = ""

[[plugins]]
package = "netlify-plugin-ghost-markdown"

    [plugins.inputs]
    ghostURL = "https://pubs.ghost.io"
    ghostKey = "ddcfb6aa38bf16e51b082fb3bc"
    postsDir = "./src/site/articles/"
    assetsDir = "./src/site/assets/uploads/images/"
    cacheFile = "./ghostMarkdownCache.json"